- hosts: all
  become: yes
  tasks:
  - name: Update Debian OSs
    apt:
     upgrade: dist
     update_cache: yes
     autoremove: yes
    when: ansible_os_family == 'Debian'        

  - name: Update RHEL OSs
    yum:
     name: '*'
     update_cache: yes
    when: ansible_os_family == 'Red Hat'
    
  - name: Reboot system if required
    command: shutdown -r now 'Rebooting to complete system upgrade' removes=/var/run/reboot-required
